_extends: .github

repository:
  name: discord-tokens
  description: "A repo to commit leaked tokens to, so they get reset. Repo cleans itself every week"

branches:
  - name: main
    protection:
      required_status_checks:
        contexts:
          - "ESLint"
